#! /usr/bin/php
<?php

date_default_timezone_set("Asia/Kuala_Lumpur");

require __DIR__ . './../../vendor/autoload.php';
require __DIR__ . './../commons.php';

use Arma7x\LocalServices\PublicInfoBanjir;

function printPublicInfoBanjirRiverLevel($state = "KDH") {
  foreach (PublicInfoBanjir::getRiverLevel($state)["data"] as $row) {
    foreach ($row as $key => $value) {
      echo str_pad("\033[36m" . $key . " ", 30, "=") . "\033[39m" . "=> " . $value . "\r\n";
    }
    echo "\r\n";
  }
}

printPublicInfoBanjirRiverLevel($argv[1]);
